
enum
{
	WHITE_SPACE = 0,
	// ———— PREPROCESSOR
	LINE_COMMENT = 1,  // //.*
	BLOCK_COMMENT = 2,  /* (.|\n)* */
	PREPROCESSOR_INSTRUCTION = 3,  // #.*
	GLOBABL_SYMBOL = 4,  // ~

	// ———— ENCAPSULATION/ENUMERATION
	OPEN_ENCAPSULATE = 100,  // (
	CLOSE_ENCAPSULATE = 101,  // )
	ENUMERATOR = 102,  // ,
	OPEN_ENUMERATION = 103,  // {
	CLOSE_ENUMERATION = 104,  // }

	// ———— KEY WORDS
	// ——— KEY WORDS::INTEGER
	SMALL_KEYWORD = 201,
	SHORT_KEYWORD = 202,
	INT_KEYWORD = 203,
	LONG_KEYWORD = 204,
	LARGE_KEYWORD = 205,
	// ———— KEY WORDS::FLOATING POINT
	DOUBLE_KEYWORD = 206,
	// ———— BRANCHING ————
	FOR_KEYWORD = 207,
	DO_KEYWORD = 208,
	WHILE_KEYWORD = 209,
	IF_KEYWORD = 210,
	ELIF_KEYWORD = 211,
	ELSE_KEYWORD = 212,

	// ———— LITERALS
	BINARY_INT_LITERAL = 300,
	OCTAL_INT_LITERAL = 301,
	DECIMAL_INT_LITERAL = 302,
	HEXIDECIMAL_INT_LITERAL = 303,
	DOUBLE_LITERAL = 304,
	CHARACTER_LITERAL = 305,
	STRING_LITERAL = 306,

	// ———— OPERATORS
	// ———— OPERATORS::ASSIGN
	_OPERATOR = 438,  // 
	ASSIGN_OPERATOR = 400,  // =
	ADDITION_ASSIGN_OPERATOR = 401,  // +=
	SUBTRACT_ASSIGN_OPERATOR = 402,  // -=
	MULTIPLY_ASSIGN_OPERATOR = 403,  // *=
	DIVIDE_ASSIGN_OPERATOR = 404,  // /=
	AND_ASSIGN_OPERATOR = 405,  // &&= (a &&= b   ≡   a = a && b)
	OR_ASSIGN_OPERATOR = 406,  // ||= (a||= b   ≡   a = a || b)
	BITWISE_OR_ASSIGN_OPERATOR = 407,  // |=
	BITWISE_AND_ASSIGN_OPERATOR = 408,  // &=
	XOR_ASSIGN_OPERATOR = 409,  // ^=
	BIT_SHIFT_LEFT_ASSIGN_OPERATOR = 410,  // <<=
	BIT_SHIFT_RIGHT_ASSIGN_OPERATOR = 411,  // >>=
	// ———— OPERATORS::MATHEMATICAL
	ADDITION_OPERATOR = 412,  // +
	SUBTRACTION_OPERATOR = 413,  // -
	MULTIPLY_OPERATOR = 414,  // *
	DIVIDE_OPERATOR = 415,  // /
	MODULO_OPERATOR = 416,  // %
	INCREMENT_OPERATOR = 417,  // ++
	DECREMENT_OPERATOR = 418,  // --
	SQUARE_OPERATOR = 419,  // **
	// ———— OPERATORS::LOGICAL
	EQUIVALENCE_OPERATOR = 420,  // ==
	NON_EQUIVALENCE_OPERATOR = 421,  // !=
	OR_OPERATOR = 422,  // ||
	AND_OPERATOR = 423,  // &&
	LESS_THAN_OPERATOR = 424,  // <
	GREATER_THAN_OPERATOR = 425,  // >
	LESS_THAN_EQUAL_OPERATOR = 426,  // <=
	GREATER_THAN_EQUAL_OPERATOR = 427,  // >=
	BOOLEAN_NOT_OPERATOR = 428,  // !
	// ———— OPERATORS::BINARY
	COMPLEMENT_OPERATOR = 429,  // !- (equivalent to 0xFFFFFFFF ^ value)
	BITWISE_OR_OPERATOR = 430,  // |
	BITWISE_AND_OPERATOR = 431,  // &
	XOR_OPERATOR = 432,  // ^
	BIT_SHIFT_LEFT_OPERATOR = 433,  // <<
	BIT_SHIFT_RIGHT_OPERATOR = 434,  // >>
	// ———— OPERATORS::ADDRESSING
	DEREFERENCE_OPERATOR = 435,  // $
	REFERENCE_OPERATOR = 436,  // @
	DOT_OPERATOR = 437,  // . (for accessing an offset from an address of an array or structure/composition)
};