
/***********************************************************************************************************************
*                                                                                                                      *
*   created by: MPZinke                                                                                                *
*   on ..                                                                                                              *
*                                                                                                                      *
*   DESCRIPTION: TEMPLATE                                                                                              *
*   BUGS:                                                                                                              *
*   FUTURE:                                                                                                            *
*                                                                                                                      *
***********************************************************************************************************************/


#include "Symbol.h"
#include "Global.h"
#include "LexerLengthMatching.h"


Symbol* find_symbol_by_(uint16_t type)
{
	for(uint16_t x = 0; x < sizeof(SYMBOLS) / sizeof(Symbol) && x < UINT16_MAX; x++)
	{
		if(SYMBOLS[x].type == type) return SYMBOLS+x;
	}
	return NULL;
}


Symbol SYMBOLS[MAX_SYMBOL_COUNT] =
{
	{
		"",
		white_space_length,
		true,
		"WHITE_SPACE",
		WHITE_SPACE
	},
	// ———— PREPROCESSOR
	{
		"",
		line_comment_length,
		true,
		"LINE_COMMENT",
		LINE_COMMENT
	},
	{
		"",
		block_comment_length,
		true,
		"BLOCK_COMMENT",
		BLOCK_COMMENT
	},
	{
		"",
		preprocessor_instruction_length,
		false,
		"PREPROCESSOR_INSTRUCTION",
		PREPROCESSOR_INSTRUCTION
	},
	// ———— OTHER
	{
		"~",
		match_symbol_length,
		false,
		"GLOBAL_SYMBOL",
		GLOBAL_SYMBOL
	},
	{
		";",
		match_symbol_length,
		false,
		"SEMI_COLON",
		SEMI_COLON
	},

	// ———— BRANCHING
	{
		"for",
		match_symbol_length,
		false,
		"FOR_KEYWORD",
		FOR_KEYWORD
	},
	{
		"do",
		match_symbol_length,
		false,
		"DO_KEYWORD",
		DO_KEYWORD
	},
	{
		"while",
		match_symbol_length,
		false,
		"WHILE_KEYWORD",
		WHILE_KEYWORD
	},
	{
		"break",
		match_symbol_length,
		false,
		"BREAK_KEYWORD",
		BREAK_KEYWORD
	},
	{
		"continue",
		match_symbol_length,
		false,
		"CONTINUE_KEYWORD",
		CONTINUE_KEYWORD
	},
	{
		"if",
		match_symbol_length,
		false,
		"IF_KEYWORD",
		IF_KEYWORD
	},
	{
		"elif",
		match_symbol_length,
		false,
		"ELIF_KEYWORD",
		ELIF_KEYWORD
	},
	{
		"else",
		match_symbol_length,
		false,
		"ELSE_KEYWORD",
		ELSE_KEYWORD
	},

	// ———— ENCAPSULATION/ENUMERATION
	{
		"(",
		match_symbol_length,
		false,
		"OPEN_ENCAPSULATE",
		OPEN_ENCAPSULATE
	},
	{
		")",
		match_symbol_length,
		false,
		"CLOSE_ENCAPSULATE",
		CLOSE_ENCAPSULATE
	},
	{
		",",
		match_symbol_length,
		false,
		"ENUMERATOR",
		ENUMERATOR
	},
	{
		"{",
		match_symbol_length,
		false,
		"OPEN_ENUMERATION",
		OPEN_ENUMERATION
	},
	{
		"}",
		match_symbol_length,
		false,
		"CLOSE_ENUMERATION",
		CLOSE_ENUMERATION
	},

	// ———— KEY WORDS
	{
		"char",
		match_symbol_length,
		false,
		"CHAR_KEYWORD",
		CHAR_KEYWORD
	},
	// ——— KEY WORDS::INTEGER
	{
		"small",
		match_symbol_length,
		false,
		"SMALL_KEYWORD",
		SMALL_KEYWORD
	},
	{
		"short",
		match_symbol_length,
		false,
		"SHORT_KEYWORD",
		SHORT_KEYWORD
	},
	{
		"int",
		match_symbol_length,
		false,
		"INT_KEYWORD",
		INT_KEYWORD
	},
	{
		"long",
		match_symbol_length,
		false,
		"LONG_KEYWORD",
		LONG_KEYWORD
	},
	{
		"large",
		match_symbol_length,
		false,
		"LARGE_KEYWORD",
		LARGE_KEYWORD
	},
	// ———— KEY WORDS::FLOATING POINT
	{
		"double",
		match_symbol_length,
		false,
		"DOUBLE_KEYWORD",
		DOUBLE_KEYWORD
	},
	// ———— KEY WORDS::OTHER
	{
		"comp",
		match_symbol_length,
		false,
		"COMP_KEYWORD",
		COMP_KEYWORD
	},
	{
		"main",
		match_symbol_length,
		false,
		"MAIN_KEYWORD",
		MAIN_KEYWORD
	},
	{
		"return",
		match_symbol_length,
		false,
		"RETURN_KEYWORD",
		RETURN_KEYWORD
	},

	// ———— LITERALS
	{
		"",
		binary_int_literal_length,
		false,
		"BINARY_INT_LITERAL",
		BINARY_INT_LITERAL
	},
	{
		"",
		octal_int_literal_length,
		false,
		"OCTAL_INT_LITERAL",
		OCTAL_INT_LITERAL
	},
	{
		"",
		decimal_int_literal_length,
		false,
		"DECIMAL_INT_LITERAL",
		DECIMAL_INT_LITERAL
	},
	{
		"",
		hexidecimal_int_literal_length,
		false,
		"HEXIDECIMAL_INT_LITERAL",
		HEXIDECIMAL_INT_LITERAL
	},
	{
		"",
		double_literal_length,
		false,
		"DOUBLE_LITERAL",
		DOUBLE_LITERAL
	},
	{
		"",
		character_literal_length,
		false,
		"CHARACTER_LITERAL",
		CHARACTER_LITERAL
	},
	{
		"",
		string_literal_length,
		false,
		"STRING_LITERAL",
		STRING_LITERAL
	},

	// ———— OPERATORS
	// ———— OPERATORS::ASSIGN
	{
		"=",
		match_symbol_length,
		false,
		"ASSIGN_OPERATOR",
		ASSIGN_OPERATOR
	},
	{
		"+=",
		match_symbol_length,
		false,
		"ADDITION_ASSIGN_OPERATOR",
		ADDITION_ASSIGN_OPERATOR
	},
	{
		"-=",
		match_symbol_length,
		false,
		"SUBTRACT_ASSIGN_OPERATOR",
		SUBTRACT_ASSIGN_OPERATOR
	},
	{
		"*=",
		match_symbol_length,
		false,
		"MULTIPLY_ASSIGN_OPERATOR",
		MULTIPLY_ASSIGN_OPERATOR
	},
	{
		"/=",
		match_symbol_length,
		false,
		"DIVIDE_ASSIGN_OPERATOR",
		DIVIDE_ASSIGN_OPERATOR
	},
	{
		"&&=",  // (a &&= b   ≡   a),
		match_symbol_length,
		false,
		"AND_ASSIGN_OPERATOR",
		AND_ASSIGN_OPERATOR
	},
	{
		"||=",  // (a||= b   ≡   a),
		match_symbol_length,
		false,
		"OR_ASSIGN_OPERATOR",
		OR_ASSIGN_OPERATOR
	},
	{
		"|=",
		match_symbol_length,
		false,
		"BITWISE_OR_ASSIGN_OPERATOR",
		BITWISE_OR_ASSIGN_OPERATOR
	},
	{
		"&=",
		match_symbol_length,
		false,
		"BITWISE_AND_ASSIGN_OPERATOR",
		BITWISE_AND_ASSIGN_OPERATOR
	},
	{
		"^=",
		match_symbol_length,
		false,
		"XOR_ASSIGN_OPERATOR",
		XOR_ASSIGN_OPERATOR
	},
	{
		"<<=",
		match_symbol_length,
		false,
		"BIT_SHIFT_LEFT_ASSIGN_OPERATOR",
		BIT_SHIFT_LEFT_ASSIGN_OPERATOR
	},
	{
		">>=",
		match_symbol_length,
		false,
		"BIT_SHIFT_RIGHT_ASSIGN_OPERATOR",
		BIT_SHIFT_RIGHT_ASSIGN_OPERATOR
	},
	{
		"<=>",
		match_symbol_length,
		false,
		"SWAP_OPERATOR",
		SWAP_OPERATOR
	},
	// ———— OPERATORS::MATHEMATICAL
	{
		"+",
		match_symbol_length,
		false,
		"ADDITION_OPERATOR",
		ADDITION_OPERATOR
	},
	{
		"-",
		match_symbol_length,
		false,
		"SUBTRACTION_OPERATOR",
		SUBTRACTION_OPERATOR
	},
	{
		"*",
		match_symbol_length,
		false,
		"MULTIPLY_OPERATOR",
		MULTIPLY_OPERATOR
	},
	{
		"/",
		match_symbol_length,
		false,
		"DIVIDE_OPERATOR",
		DIVIDE_OPERATOR
	},
	{
		"%",
		match_symbol_length,
		false,
		"MODULO_OPERATOR",
		MODULO_OPERATOR
	},
	{
		"++",
		match_symbol_length,
		false,
		"INCREMENT_OPERATOR",
		INCREMENT_OPERATOR
	},
	{
		"--",
		match_symbol_length,
		false,
		"DECREMENT_OPERATOR",
		DECREMENT_OPERATOR
	},
	{
		"**",
		match_symbol_length,
		false,
		"SQUARE_OPERATOR",
		SQUARE_OPERATOR
	},
	// ———— OPERATORS::LOGICAL
	{
		"==",
		match_symbol_length,
		false,
		"EQUIVALENCE_OPERATOR",
		EQUIVALENCE_OPERATOR
	},
	{
		"!=",
		match_symbol_length,
		false,
		"NON_EQUIVALENCE_OPERATOR",
		NON_EQUIVALENCE_OPERATOR
	},
	{
		"||",
		match_symbol_length,
		false,
		"OR_OPERATOR",
		OR_OPERATOR
	},
	{
		"&&",
		match_symbol_length,
		false,
		"AND_OPERATOR",
		AND_OPERATOR
	},
	{
		"<",
		match_symbol_length,
		false,
		"LESS_THAN_OPERATOR",
		LESS_THAN_OPERATOR
	},
	{
		">",
		match_symbol_length,
		false,
		"GREATER_THAN_OPERATOR",
		GREATER_THAN_OPERATOR
	},
	{
		"<=",
		match_symbol_length,
		false,
		"LESS_THAN_EQUAL_OPERATOR",
		LESS_THAN_EQUAL_OPERATOR
	},
	{
		">=",
		match_symbol_length,
		false,
		"GREATER_THAN_EQUAL_OPERATOR",
		GREATER_THAN_EQUAL_OPERATOR
	},
	{
		"!",
		match_symbol_length,
		false,
		"BOOLEAN_NOT_OPERATOR",
		BOOLEAN_NOT_OPERATOR
	},
	// ———— OPERATORS::BINARY
	{
		"!-",  // (equivalent to 0xFFFFFFFF ^ value),
		match_symbol_length,
		false,
		"COMPLEMENT_OPERATOR",
		COMPLEMENT_OPERATOR
	},
	{
		"|",
		match_symbol_length,
		false,
		"BITWISE_OR_OPERATOR",
		BITWISE_OR_OPERATOR
	},
	{
		"&",
		match_symbol_length,
		false,
		"BITWISE_AND_OPERATOR",
		BITWISE_AND_OPERATOR
	},
	{
		"^",
		match_symbol_length,
		false,
		"XOR_OPERATOR",
		XOR_OPERATOR
	},
	{
		"<<",
		match_symbol_length,
		false,
		"BIT_SHIFT_LEFT_OPERATOR",
		BIT_SHIFT_LEFT_OPERATOR
	},
	{
		">>",
		match_symbol_length,
		false,
		"BIT_SHIFT_RIGHT_OPERATOR",
		BIT_SHIFT_RIGHT_OPERATOR
	},
	// ———— OPERATORS::ADDRESSING
	{
		"$",
		match_symbol_length,
		false,
		"DEREFERENCE_OPERATOR",
		DEREFERENCE_OPERATOR
	},
	{
		"@",
		match_symbol_length,
		false,
		"REFERENCE_OPERATOR",
		REFERENCE_OPERATOR
	},
	{
		".",
		match_symbol_length,
		false,
		"DOT_OPERATOR",
		DOT_OPERATOR
	},
	{
		"->",
		match_symbol_length,
		false,
		"ARROW_OPERATOR",
		ARROW_OPERATOR
	},

	// ————— OTHER
	{
		"",
		identifier_length,
		false,
		"IDENTIFIER",
		IDENTIFIER
	},
	{
		"",
		unknown_char_length,
		false,
		"UNKNOWN_CHAR",
		UNKNOWN_CHAR
	}
};
